# 1. Create a 3x3x3 array with random values

In [3]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.80502385 0.25872595 0.65498585]
  [0.02301867 0.61880511 0.66235566]
  [0.34307327 0.81405211 0.9075483 ]]

 [[0.07024675 0.54066321 0.22561147]
  [0.64482607 0.81980546 0.31259866]
  [0.20498209 0.07328012 0.53385791]]

 [[0.30394295 0.18911619 0.92520677]
  [0.5563754  0.17613861 0.63466605]
  [0.71166026 0.85773257 0.07208064]]]


# # 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
b = np.diag(1+np.arange(4), k = -1)
print (b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
c = np.zeros ((8,8), dtype=int)
c[1::2, ::2]= 1
c[::2, 1::2] = 1
print (c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.27951547 0.70107222 0.38349512 0.34889578 0.93048132]
 [0.65837416 0.         1.         0.92682387 0.5242661 ]
 [0.28106895 0.34935725 0.2937745  0.5028181  0.1015084 ]
 [0.77636394 0.24715108 0.37576565 0.01670577 0.4893525 ]
 [0.61948455 0.18027204 0.02506491 0.18191328 0.20966405]]


# 5.  How to find common values between two arrays?

In [8]:
import numpy as np
array1 = np.array([10, 20, 40, 60,80,45])
print("Array1: ",array1)
array2 = [10, 30, 40,80,90,50,45]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [10 20 40 60 80 45]
Array2:  [10, 30, 40, 80, 90, 50, 45]
Common values between two arrays:
[10 40 45 80]


# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [22]:
A1 = np.random.randint(0,2,10)
A2 = np.random.randint(0,2,10)
equal = np.allclose(A1,A2)
print(A1)
print(A2)
print(equal)

[0 0 1 0 0 0 0 0 1 1]
[1 1 1 1 0 1 1 1 0 1]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [29]:
vector = np.random.random(10)
print("The Random Vector :\n", vector)
vector[vector.argmax()] = 0
print("The Replace vector :\n",vector)

The Random Vector :
 [0.19373803 0.68188704 0.89407411 0.30402103 0.26096588 0.4428244
 0.32077853 0.92427701 0.06087765 0.26239529]
The Replace vector :
 [0.19373803 0.68188704 0.89407411 0.30402103 0.26096588 0.4428244
 0.32077853 0.         0.06087765 0.26239529]


# 9. How to print all the values of an array?

In [43]:
import numpy as np 

with np.printoptions(precision = 3): 
     print(np.zeros((10,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [75]:
X = np.random.rand(3,3)

Y = X - X.mean(axis=1).reshape(-1, 1)

Y

array([[-0.11212106022673451 , -0.03370530329346333 ,
         0.14582636352019762 ],
       [ 0.00447635197683216 ,  0.06123672327748475 ,
        -0.06571307525431713 ],
       [-0.016851778273105578, -0.1812577390374548  ,
         0.19810951731056037 ]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [60]:
Z = np.ones(5)
print(Z)
I = np.random.randint(0,len(Z),10)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 1. 1. 1. 1.]
[1 4 2 4 2 4 0 3 0 3]
[3. 2. 3. 3. 4.]


# 12.How to get the diagonal of a dot product?

In [79]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version
print(A)
print(B)

np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

[[2 3 1]
 [0 3 8]
 [7 9 0]]
[[6 9 7]
 [7 0 7]
 [7 1 4]]


array([ 40,   8, 112])

# 13.How to find the most frequent value in an array?

In [69]:
arr = np.random.randint(0,10,20)
print (arr)
print('rank:', np.bincount(arr).argmax())

[5 9 7 7 1 5 6 3 7 8 1 0 0 7 8 2 3 9 6 4]
rank: 7


# 14.How to get the n largest values of an array

In [81]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[95 96 97 98 99]


# 15.How to create a record array from a regular array?

In [87]:
a = np.array([("Lets", 1, 3),
              ("Upgrade", 3, 2)])
b = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

print(Z)
print(R)

[['Lets' '1' '3']
 ['Upgrade' '3' '2']]
[(b'Lets', 1., 3) (b'Upgrade', 3., 2)]
